# Generated by Django 5.2 on 2025-04-07 06:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Node',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Nazwa węzła (np. Node 1)', max_length=50)),
                ('ip_address', models.GenericIPAddressField(help_text='Adres IP węzła', unpack_ipv4=True)),
                ('status', models.CharField(default='online', help_text='Status węzła, np. online/offline', max_length=20)),
                ('last_seen', models.DateTimeField(auto_now=True, help_text='Data i czas ostatniego kontaktu')),
            ],
        ),
        migrations.CreateModel(
            name='ActiveConnection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('connected_at', models.DateTimeField(auto_now_add=True, help_text='Data i czas nawiązania połączenia')),
                ('node', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='active_connection', to='simulation.node')),
            ],
        ),
        migrations.CreateModel(
            name='Transmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.TextField(help_text='Przesyłane dane (np. ciąg bitów)')),
                ('timestamp', models.DateTimeField(auto_now_add=True, help_text='Data i czas rozpoczęcia transmisji')),
                ('delay', models.FloatField(default=0.0, help_text='Opóźnienie transmisji (w sekundach)')),
                ('packet_loss_percentage', models.FloatField(default=0.0, help_text='Procent utraconych pakietów')),
                ('error_info', models.JSONField(blank=True, help_text='Informacje o wprowadzonych błędach (np. typ i ilość)', null=True)),
                ('destination', models.ForeignKey(help_text='Węzeł odbierający dane', on_delete=django.db.models.deletion.CASCADE, related_name='transmissions_received', to='simulation.node')),
                ('source', models.ForeignKey(help_text='Węzeł wysyłający dane', on_delete=django.db.models.deletion.CASCADE, related_name='transmissions_sent', to='simulation.node')),
            ],
        ),
        migrations.CreateModel(
            name='EventLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_time', models.DateTimeField(auto_now_add=True, help_text='Data i czas zdarzenia')),
                ('crc_code', models.CharField(help_text='Wygenerowany kod CRC', max_length=64)),
                ('error_type', models.CharField(blank=True, help_text="Typ błędu, np. 'single', 'double', 'burst'", max_length=50)),
                ('error_count', models.IntegerField(default=0, help_text='Liczba wprowadzonych błędów')),
                ('verification_result', models.BooleanField(help_text='Wynik weryfikacji (True - brak błędów, False - wykryto błąd)')),
                ('details', models.TextField(blank=True, help_text='Dodatkowe informacje o zdarzeniu')),
                ('transmission', models.ForeignKey(help_text='Transmisja, do której odnosi się zdarzenie', on_delete=django.db.models.deletion.CASCADE, related_name='events', to='simulation.transmission')),
            ],
        ),
    ]
